name: Build Orange Pi

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-opi:
    name: Orange Pi Zero 2W (Trixie/FB0)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build OPi Binary
        run: |
          chmod +x scripts/build-opi-trixie-fb0.sh
          ./scripts/build-opi-trixie-fb0.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hamclock-opi-trixie-fb0
          path: |
            build-opi-trixie-fb0/hamclock-next
            build-opi-trixie-fb0/*.deb

  build-opi-bookworm:
    name: Orange Pi Zero 2W (Bookworm/FB0)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build OPi Binary
        run: |
          chmod +x scripts/build-opi-bookworm-fb0.sh
          ./scripts/build-opi-bookworm-fb0.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hamclock-opi-bookworm-fb0
          path: |
            build-opi-bookworm-fb0/hamclock-next
            build-opi-bookworm-fb0/*.deb
