name: Build RPi

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-rpi:
    name: Raspberry Pi 3B+ (Bullseye/FB0)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build RPi Binary
        run: |
          chmod +x scripts/build-rpi-bullseye-fb0.sh
          ./scripts/build-rpi-bullseye-fb0.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hamclock-rpi-bullseye-fb0
          path: |
            build-rpi-bullseye-fb0/hamclock-next
            build-rpi-bullseye-fb0/*.deb

  build-rpi-bullseye-x11:
    name: Raspberry Pi X11 (Bullseye)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build RPi X11 Binary
        run: |
          chmod +x scripts/build-rpi-bullseye-x11.sh
          ./scripts/build-rpi-bullseye-x11.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hamclock-rpi-bullseye-x11
          path: |
            build-rpi-bullseye-x11/hamclock-next
            build-rpi-bullseye-x11/*.deb

  build-rpi-bookworm-x11:
    name: Raspberry Pi X11 (Bookworm)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build RPi X11 Binary
        run: |
          chmod +x scripts/build-rpi-bookworm-x11.sh
          ./scripts/build-rpi-bookworm-x11.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hamclock-rpi-bookworm-x11
          path: |
            build-rpi-bookworm-x11/hamclock-next
            build-rpi-bookworm-x11/*.deb

  build-rpi-trixie-x11:
    name: Raspberry Pi X11 (Trixie)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build RPi X11 Binary
        run: |
          chmod +x scripts/build-rpi-trixie-x11.sh
          ./scripts/build-rpi-trixie-x11.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hamclock-rpi-trixie-x11
          path: |
            build-rpi-trixie-x11/hamclock-next
            build-rpi-trixie-x11/*.deb
